---
# Area Labels
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/renovate
  color: "0e8a16"
- name: area/terraform
  color: "0e8a16"
# Renovate Types
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/grafana-dashboard
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
- name: renovate/terraform
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# Issue Types
- name: issue/bug
  color: "ff0000"
- name: issue/feature
  color: "00ff00"
- name: issue/chore
  color: "0000ff"
# Uncategorized
- name: community
  color: "370fb2"
- name: hold
  color: "ee0701"